apiVersion: apps/v1
kind: Deployment
metadata:
  name: summarie
  labels:
    app: summarie
spec:
  replicas: 3
  selector:
    matchLabels:
      app: summarie
  template:
    metadata:
      labels:
        app: summarie
    spec:
      containers:
      - name: summarie
        image: ghcr.io/saadaltafofficial/summarie:sha-713cceaa313bf8285f7aa65789151e567c0fa099
        # Image will be automatically updated by CI/CD pipeline
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: github-container-registry